-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "ava_alquiler" (
    "alq_id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "alq_monto" INT8 NOT NULL,
    "alq_fechapago" TIMESTAMP(6) NOT NULL,
    "alq_contrato" STRING(500),
    "alq_estado" STRING(1) NOT NULL,
    "alq_fechacreacion" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "prop_id" INT8,
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),

    CONSTRAINT "ava_alquiler_pk" PRIMARY KEY ("alq_id")
);

-- CreateTable
CREATE TABLE "ava_alquilermensual" (
    "alqm_id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "alqm_identificador" STRING(15) NOT NULL,
    "alqm_fechainicio" TIMESTAMP(6) NOT NULL,
    "alqm_fechafin" TIMESTAMP(6) NOT NULL,
    "alqm_montototal" INT8 NOT NULL,
    "alqm_montopagado" INT8 NOT NULL,
    "alqm_fechapago" TIMESTAMP(6),
    "alqm_estado" STRING(1) NOT NULL,
    "alqm_fechacreacion" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "alq_id" INT8,
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),

    CONSTRAINT "ava_alquilermensual_pk" PRIMARY KEY ("alqm_id")
);

-- CreateTable
CREATE TABLE "ava_cliente" (
    "cli_id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "cli_nombre" STRING(30) NOT NULL,
    "cli_papellido" STRING(30) NOT NULL,
    "cli_sapellido" STRING(30),
    "cli_cedula" STRING(15) NOT NULL,
    "cli_telefono" STRING(15) NOT NULL,
    "cli_correo" STRING(50) NOT NULL,
    "cli_fechacreacion" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "cli_direccion" STRING(200),
    "cli_estadocivil" STRING(20),
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),

    CONSTRAINT "ava_cliente_pk" PRIMARY KEY ("cli_id")
);

-- CreateTable
CREATE TABLE "ava_clientexalquiler" (
    "alq_id" INT8 NOT NULL,
    "cli_id" INT8 NOT NULL,
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),

    CONSTRAINT "pk_ava_clientexalquiler" PRIMARY KEY ("alq_id","cli_id")
);

-- CreateTable
CREATE TABLE "ava_deposito" (
    "depo_id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "depo_montoactual" INT8 NOT NULL,
    "depo_total" INT8 NOT NULL,
    "depo_montodevuelto" INT8,
    "depo_montocastigo" INT8,
    "depo_descmontodevuelto" STRING(50),
    "depo_descrmontocastigo" STRING(50),
    "depo_fechadevolucion" TIMESTAMP(6),
    "depo_fechacreacion" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "alq_id" INT8,
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),

    CONSTRAINT "ava_deposito_pk" PRIMARY KEY ("depo_id")
);

-- CreateTable
CREATE TABLE "ava_edificio" (
    "edi_id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "edi_identificador" STRING(15) NOT NULL,
    "edi_descripcion" STRING(50),
    "edi_direccion" STRING(200),
    "edi_codigopostal" STRING(10),
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),

    CONSTRAINT "pk_ava_edificio" PRIMARY KEY ("edi_id")
);

-- CreateTable
CREATE TABLE "ava_pago" (
    "pag_id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "pag_monto" INT8 NOT NULL,
    "pag_descripcion" STRING(50),
    "pag_cuenta" STRING(50),
    "pag_estado" STRING(1) NOT NULL,
    "pag_fechapago" TIMESTAMP(6) NOT NULL,
    "pag_metodopago" STRING(30),
    "pag_banco" STRING(50),
    "pag_referencia" STRING(100),
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),
    "res_id" INT8,
    "alqm_id" INT8,
    "depo_id" INT8,

    CONSTRAINT "ava_pago_pk" PRIMARY KEY ("pag_id")
);

-- CreateTable
CREATE TABLE "ava_propiedad" (
    "prop_id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "prop_identificador" STRING(15) NOT NULL,
    "prop_descripcion" STRING(50),
    "edi_id" INT8,
    "tipp_id" INT8,
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),

    CONSTRAINT "ava_propiedad_pk" PRIMARY KEY ("prop_id")
);

-- CreateTable
CREATE TABLE "ava_reservacion" (
    "res_id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "res_nombrecliente" STRING(50) NOT NULL,
    "res_telefonocliente" STRING(15),
    "res_correocliente" STRING(50),
    "res_fechaentrada" TIMESTAMP(6) NOT NULL,
    "res_fechasalida" TIMESTAMP(6) NOT NULL,
    "res_montototal" INT8 NOT NULL,
    "res_montoactual" INT8 NOT NULL,
    "res_estado" STRING(1) NOT NULL,
    "res_fechacreacion" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "prop_id" INT8,
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),

    CONSTRAINT "ava_reservacion_pk" PRIMARY KEY ("res_id")
);

-- CreateTable
CREATE TABLE "ava_servicio" (
    "ser_id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ser_codigo" STRING(30) NOT NULL,
    "ser_nombre" STRING(30) NOT NULL,
    "ser_servicio" STRING(40),
    "ser_negocio" STRING(80),
    "ser_mediopago" STRING(30),
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),

    CONSTRAINT "ava_servicio_pk" PRIMARY KEY ("ser_id")
);

-- CreateTable
CREATE TABLE "ava_gasto" (
    "gas_id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "gas_tipo" STRING(1) NOT NULL,
    "gas_concepto" STRING(60) NOT NULL,
    "gas_descripcion" STRING(200),
    "gas_monto" INT8 NOT NULL,
    "gas_fecha" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "gas_estado" STRING(1) NOT NULL DEFAULT 'A',
    "gas_metodopago" STRING(30),
    "gas_cuenta" STRING(50),
    "gas_banco" STRING(50),
    "gas_referencia" STRING(100),
    "gas_comprobante" STRING(500),
    "edi_id" INT8 NOT NULL,
    "prop_id" INT8,
    "ser_id" INT8,
    "usu_id" INT8,
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),

    CONSTRAINT "ava_gasto_pk" PRIMARY KEY ("gas_id")
);

-- CreateTable
CREATE TABLE "ava_anulaciongasto" (
    "ang_id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ang_motivo" STRING(50) NOT NULL,
    "ang_descripcion" STRING(200),
    "ang_montooriginal" INT8 NOT NULL,
    "ang_montofinal" INT8 NOT NULL,
    "ang_fechaanulacion" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "gas_id" INT8 NOT NULL,
    "usu_id" INT8 NOT NULL,
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),

    CONSTRAINT "pk_ava_anulaciongasto" PRIMARY KEY ("ang_id")
);

-- CreateTable
CREATE TABLE "ava_tipopropiedad" (
    "tipp_id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tipp_nombre" STRING(30) NOT NULL,
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),

    CONSTRAINT "ava_tipopropiedad_pk" PRIMARY KEY ("tipp_id")
);

-- CreateTable
CREATE TABLE "ava_usuario" (
    "usu_id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "usu_nombre" STRING(30) NOT NULL,
    "usu_papellido" STRING(30) NOT NULL,
    "usu_sapellido" STRING(30),
    "usu_cedula" STRING(15) NOT NULL,
    "usu_correo" STRING(50) NOT NULL,
    "usu_contrasena" STRING(500) NOT NULL,
    "usu_telefono" STRING(15),
    "usu_fechacreacion" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "usu_estado" STRING(1) NOT NULL,
    "usu_rol" STRING(1) NOT NULL,
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),

    CONSTRAINT "ava_usuario_pk" PRIMARY KEY ("usu_id")
);

-- CreateTable
CREATE TABLE "parametros" (
    "par_nombre" STRING(30),
    "par_logo" STRING(500),
    "par_correo" STRING(50),
    "par_descripcion" STRING(200),
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),

    CONSTRAINT "parametros_pkey" PRIMARY KEY ("rowid")
);

-- CreateTable
CREATE TABLE "ava_alquilercancelado" (
    "alqc_id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "alqc_motivo" STRING(50) NOT NULL,
    "alqc_montodevuelto" INT8,
    "alqc_castigo" INT8,
    "alqc_motivomontodevuelto" STRING(50),
    "alqc_motivocastigo" STRING(50),
    "alqc_fecha_cancelacion" TIMESTAMP(6) NOT NULL,
    "alqc_fechacreacion" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "alq_id" INT8,
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),

    CONSTRAINT "pk_ava_alquilercancelado" PRIMARY KEY ("alqc_id")
);

-- CreateTable
CREATE TABLE "ava_anulacionpago" (
    "anp_id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "anp_motivo" STRING(50) NOT NULL,
    "anp_descripcion" STRING(50) NOT NULL,
    "anp_montooriginal" INT8 NOT NULL,
    "anp_montofinal" INT8 NOT NULL,
    "anp_fechaanulacion" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "pag_id" INT8,
    "usu_id" INT8,
    "rowid" INT8 NOT NULL DEFAULT unique_rowid(),

    CONSTRAINT "pk_ava_anulacionpago" PRIMARY KEY ("anp_id")
);

-- CreateIndex
CREATE INDEX "ava_alquiler_fk01" ON "ava_alquiler"("prop_id");

-- CreateIndex
CREATE UNIQUE INDEX "ava_cliente_unq01" ON "ava_cliente"("cli_cedula");

-- CreateIndex
CREATE UNIQUE INDEX "ava_cliente_unq02" ON "ava_cliente"("cli_correo");

-- CreateIndex
CREATE INDEX "ava_deposito_fk01" ON "ava_deposito"("alq_id");

-- CreateIndex
CREATE INDEX "ava_propiedad_fk01" ON "ava_propiedad"("tipp_id");

-- CreateIndex
CREATE INDEX "ava_propiedad_fk02" ON "ava_propiedad"("edi_id");

-- CreateIndex
CREATE INDEX "ava_reservacion_fk01" ON "ava_reservacion"("prop_id");

-- CreateIndex
CREATE UNIQUE INDEX "ava_servicio_unq01" ON "ava_servicio"("ser_codigo");

-- CreateIndex
CREATE INDEX "ava_gasto_fk01" ON "ava_gasto"("edi_id");

-- CreateIndex
CREATE INDEX "ava_gasto_fk02" ON "ava_gasto"("prop_id");

-- CreateIndex
CREATE INDEX "ava_gasto_fk03" ON "ava_gasto"("ser_id");

-- CreateIndex
CREATE INDEX "ava_gasto_idx01" ON "ava_gasto"("gas_tipo", "gas_fecha");

-- CreateIndex
CREATE INDEX "ava_anulaciongasto_fk01" ON "ava_anulaciongasto"("gas_id");

-- CreateIndex
CREATE INDEX "ava_anulaciongasto_fk02" ON "ava_anulaciongasto"("usu_id");

-- CreateIndex
CREATE UNIQUE INDEX "ava_usuario_unq01" ON "ava_usuario"("usu_cedula");

-- CreateIndex
CREATE UNIQUE INDEX "ava_usuario_unq02" ON "ava_usuario"("usu_correo");

-- CreateIndex
CREATE INDEX "ava_alquilercancelado_fk01" ON "ava_alquilercancelado"("alq_id");

-- CreateIndex
CREATE INDEX "ava_anulacionpago_fk01" ON "ava_anulacionpago"("pag_id");

-- CreateIndex
CREATE INDEX "ava_anulacionpago_fk02" ON "ava_anulacionpago"("usu_id");

-- AddForeignKey
ALTER TABLE "ava_alquiler" ADD CONSTRAINT "relationship34" FOREIGN KEY ("prop_id") REFERENCES "ava_propiedad"("prop_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_alquilermensual" ADD CONSTRAINT "relationship19" FOREIGN KEY ("alq_id") REFERENCES "ava_alquiler"("alq_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_clientexalquiler" ADD CONSTRAINT "relationship30" FOREIGN KEY ("alq_id") REFERENCES "ava_alquiler"("alq_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_clientexalquiler" ADD CONSTRAINT "relationship31" FOREIGN KEY ("cli_id") REFERENCES "ava_cliente"("cli_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_deposito" ADD CONSTRAINT "relationship23" FOREIGN KEY ("alq_id") REFERENCES "ava_alquiler"("alq_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_pago" ADD CONSTRAINT "relationship22" FOREIGN KEY ("alqm_id") REFERENCES "ava_alquilermensual"("alqm_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_pago" ADD CONSTRAINT "relationship24" FOREIGN KEY ("depo_id") REFERENCES "ava_deposito"("depo_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_pago" ADD CONSTRAINT "relationship21" FOREIGN KEY ("res_id") REFERENCES "ava_reservacion"("res_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_propiedad" ADD CONSTRAINT "relationship32" FOREIGN KEY ("edi_id") REFERENCES "ava_edificio"("edi_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_propiedad" ADD CONSTRAINT "relationship36" FOREIGN KEY ("tipp_id") REFERENCES "ava_tipopropiedad"("tipp_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_reservacion" ADD CONSTRAINT "relationship33" FOREIGN KEY ("prop_id") REFERENCES "ava_propiedad"("prop_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_gasto" ADD CONSTRAINT "ava_edificio_x_ava_gasto" FOREIGN KEY ("edi_id") REFERENCES "ava_edificio"("edi_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_gasto" ADD CONSTRAINT "ava_propiedad_x_ava_gasto" FOREIGN KEY ("prop_id") REFERENCES "ava_propiedad"("prop_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_gasto" ADD CONSTRAINT "ava_servicio_x_ava_gasto" FOREIGN KEY ("ser_id") REFERENCES "ava_servicio"("ser_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_gasto" ADD CONSTRAINT "ava_usuario_x_ava_gasto" FOREIGN KEY ("usu_id") REFERENCES "ava_usuario"("usu_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_anulaciongasto" ADD CONSTRAINT "ava_gasto_x_ava_anulaciongasto" FOREIGN KEY ("gas_id") REFERENCES "ava_gasto"("gas_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_anulaciongasto" ADD CONSTRAINT "ava_usuario_x_ava_anulaciongasto" FOREIGN KEY ("usu_id") REFERENCES "ava_usuario"("usu_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_alquilercancelado" ADD CONSTRAINT "ava_alquiler_x_ava_alquilercancelado" FOREIGN KEY ("alq_id") REFERENCES "ava_alquiler"("alq_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_anulacionpago" ADD CONSTRAINT "ava_pago_x_ava_anulacionpago" FOREIGN KEY ("pag_id") REFERENCES "ava_pago"("pag_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ava_anulacionpago" ADD CONSTRAINT "ava_usuario_x_ava_anulacionpago" FOREIGN KEY ("usu_id") REFERENCES "ava_usuario"("usu_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

